### ISSUE TITLE
V1.2.1 local build fails with ESPHome 2026.7.x: stream_server calls removed get_use_address()

### ISSUE THREAD

**Issue by HypeLaser** [vacuula/fang#176]
### Summary

The V1.2.1 source/local configuration no longer compiles with ESPHome 2026.7.3 because the ROS stream-server external component calls a network API that ESPHome removed.

This primarily affects source/local builds: the published `ha-esphome.yaml` does not include `comp/ros.yaml`, but `config/local.yaml` includes it by default and the repository development build uses the floating `ghcr.io/esphome/esphome` image.

### Reproduction

1. Check out tag `V1.2.1` (`a694dec`).
2. Populate the required secrets.
3. Leave the standard ESP32, Gen 3 and default package selections in `config/local.yaml`.
4. Run:

```console
esphome compile config/local.yaml
```

Environment reproduced with:

```text
ESPHome 2026.7.3
ESP-IDF 5.5.5
Standard ESP32 / Gen 3 configuration
```

### Result

Compilation fails in the external stream-server component:

```text
stream_server.cpp:52:62: error: 'get_use_address' is not a member of 'esphome::network'; did you mean 'get_use_address_to'?
ESP_LOGCONFIG(TAG, "  Address: %s:%u", esphome::network::get_use_address(), this->port_);
```

`config/comp/ros.yaml` currently pulls this component without a pinned ref:

```yaml
external_components:
  - source: github://oxan/esphome-stream-server
```

ESPHome commit `3c2dad67f4b81447f7330aa11a2eae9b454325ed` replaced `get_use_address()` with the buffer-based `get_use_address_to()` API:
https://github.com/esphome/esphome/commit/3c2dad67f4b81447f7330aa11a2eae9b454325ed

The V1.2.1 prebuilt Gen 3 ESP32 binary identifies itself as having been compiled with ESPHome 2026.3.1. Rebuilding with `esphome==2026.3.1` also succeeds locally.

### Workarounds

Either of these works:

- Build V1.2.1 with ESPHome 2026.3.1.
- Disable `comp/ros.yaml` when the stream server is not required.

### Suggested fixes

- Update or patch the stream-server component for `get_use_address_to()` compatibility.
- Pin the known-compatible ESPHome builder version used for a release instead of floating on the latest container.
- Optionally compile the supported local configurations in CI so an ESPHome API change is detected before users update.
